FROM ruby:3.1.2

# Node.jsとyarnをインストール
RUN apt-get update -qq && \
    apt-get install -y curl apt-transport-https wget && \
    curl -sL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get install -y nodejs && \
    npm install --global yarn

# PostgreSQLの公式リポジトリの追加
RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ bullseye-pgdg main' > /etc/apt/sources.list.d/pgdg.list && \
    curl -sL https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
    apt-get update -qq && \
    apt-get install -y postgresql-client-16 vim libvips42 && \
    apt-get install -y build-essential libgirepository1.0-dev poppler-utils libpoppler-glib-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# コンテナ内で作業ディレクトリを設定
WORKDIR /myapp

# GemfileとGemfile.lockをコンテナの/myappにコピー
COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemfile.lock

# Bundlerの指定されたバージョンをインストールし、bundle installを実行
RUN gem install bundler -v '2.1.4' && \
    bundle _2.1.4_ install

# アプリケーションのソースコードをコピー
COPY . /myapp

# yarnの依存関係をインストール
RUN yarn install

# Tailwind CSSをビルド
RUN yarn tailwindcss build

# 環境変数を設定
ENV RAILS_ENV=development

# コンテナがランタイムで指定されたポートをリスニングしていることをDockerに通知
EXPOSE 3000

# イメージ実行時にメインプロセスを実行するように設定
CMD ["rails", "server", "-b", "0.0.0.0"]