# Rubyの公式3.1.2イメージをベースに使用
FROM ruby:3.1.2

# Node.js 16.x をインストール
# NodeSourceの新しいセットアップスクリプトを使用
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get install -y nodejs

# PostgreSQLの公式リポジトリの追加
RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ bullseye-pgdg main' > /etc/apt/sources.list.d/pgdg.list
RUN curl -sL https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

# その他の依存関係とPostgreSQL 16クライアントツールをインストール
RUN apt-get update -qq && \
    apt-get install -y postgresql-client-16 vim libvips42 && \
    apt-get install -y build-essential libgirepository1.0-dev && \
    apt-get install -y poppler-utils libpoppler-glib-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# コンテナ内で作業ディレクトリを設定
WORKDIR /myapp

# GemfileとGemfile.lockをコンテナの/myappにコピー
COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemfile.lock

# Bundlerの指定されたバージョンをインストールし、bundle installを実行
RUN gem install bundler -v '2.1.4' && \
    bundle _2.1.4_ install

# package.jsonとpackage-lock.jsonをコピー
COPY package*.json /myapp/

# npmの依存関係をインストール
RUN npm install

# アプリケーションの残りのソースコードをコピー
COPY . /myapp

# コンテナがランタイムで指定されたポートをリスニングしていることをDockerに通知
EXPOSE 3000

# イメージ実行時にメインプロセスを実行するように設定
CMD ["rails", "server", "-b", "0.0.0.0"]
