development:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: popup_document_development

test:
  adapter: test

production:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: popup_document_production
